name: 🚀 Create release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Required to update changelog file
      pull-requests: write # Required to create release PRs
      issues: write # Required to create issues
    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071
        with:
          release-type: simple
