name: 🚀 Create release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Required to update changelog file
      pull-requests: write # Required to create release PRs
      issues: write # Required to create issues
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7
        with:
          release-type: simple
